### ISSUE TITLE
Document need for --egg option to pip

### ISSUE THREAD

**Issue by ritzk** [pjeby/winsible#2]
$ pip install winsible
$ winsible-playbook  -i ~/l <playbook>
Traceback (most recent call last):
  File "/usr/bin/winsible-playbook", line 9, in <module>
    load_entry_point('winsible==0.1.0', 'console_scripts', 'winsible-playbook')()
  File "/usr/lib/python2.7/site-packages/winsible/**init**.py", line 297, in winsible_playbook
    def winsible_playbook():    return wrap_script('ansible-playbook', True)
  File "/usr/lib/python2.7/site-packages/winsible/**init**.py", line 294, in wrap_script
    return pkg_resources.require('ansible')[0].run_script(script_name, maindict)
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1644, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'ansible-playbook'

**Comment by pjeby** [comment]
What version of ansible are you using, and how was it installed?

**Comment by ritzk** [comment]
edit: On Win7/cygwin

$ sudo pip install ansible
$ ansible --version
ansible 1.9.3

**Comment by pjeby** [comment]
Does it work if you `easy_install` ansible instead?

**Comment by pjeby** [comment]
Alternately, try the `--egg` option to pip, to request that ansible be installed as an egg.  My guess is that the problem is that `pip` doesn't install the `.egg-info/scripts` directory when not installing as an egg. (IMO that would be a compatibility bug in pip and should probably be reported, if that's the case.)

**Comment by ritzk** [comment]
- no go with easy_install. 
- no go with egg option to pip.
- I don't see /usr/lib/python2.7/ansible\* .egg-ingo/scripts file . I do see other files info egg folder.

I don't see scripts file with any libraries installed with pip. Using pip 7.1.2 on cygwin.

**Comment by pjeby** [comment]
Weird.  There's supposed to be one, per https://pythonhosted.org/setuptools/formats.html#the-scripts-subdirectory - so that seems to be a bug in pip and/or the setuptools version you're using.  I've personally never used any versions of setuptools past the 0.7 dev, so I guess it's a bug introduced since PyPA took over maintenance.

In the meantime, you can work around it by copying the ansible-playbook script to a scripts/ subdirectory of the ansible.egg-info, or by installing ansible as a zipped egg.  What I don't understand is why neither `easy_install` nor `pip --egg` installed a zipped .egg or unzipped .egg directory.  In either of those cases, there should be an "ansible-version.egg/EGG-INFO/scripts" subdirectory installed in site-packages.

**Comment by ritzk** [comment]
ok, this time egg worked , weird. 

  $ pip uninstall ansible
  $ pip install --egg ansible

**Comment by ritzk** [comment]
Use easy_install as a workaround

$ pip uninstall ansible
$ easy_install ansible
